name: Deploy API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g @redocly/cli
          mkdir -p docs

      - name: Create index.html
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <title>PAXAFE Live Risk API Documentation</title>
              <meta charset="utf-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <meta name="description" content="API documentation for PAXAFE Live Risk API v2">
              <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
              <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
              <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
              <link rel="icon" type="image/png" href="https://www.paxafe.com/favicon.ico"/>
            </head>
            <body>
              <div id="redoc"></div>
              <script>
                Redoc.init(
                  'openapi.yaml',
                  {
                    scrollYOffset: 50,
                    hideDownloadButton: false,
                    expandResponses: "200",
                    pathInMiddlePanel: true,
                    showExtensions: true,
                    sortPropsAlphabetically: true,
                    theme: {
                      spacing: {
                        unit: 5,
                        sectionVertical: 20
                      },
                      colors: {
                        primary: {
                          main: '#2196f3',
                          light: '#64b5f6',
                          dark: '#1976d2',
                          contrastText: '#ffffff'
                        },
                        success: {
                          main: '#4caf50',
                          light: '#81c784',
                          dark: '#388e3c',
                          contrastText: '#ffffff'
                        },
                        warning: {
                          main: '#ff9800',
                          light: '#ffb74d',
                          dark: '#f57c00',
                          contrastText: '#ffffff'
                        },
                        error: {
                          main: '#f44336',
                          light: '#e57373',
                          dark: '#d32f2f',
                          contrastText: '#ffffff'
                        },
                        gray: {
                          50: '#fafafa',
                          100: '#f5f5f5'
                        },
                        text: {
                          primary: '#333333',
                          secondary: '#666666'
                        }
                      },
                      typography: {
                        fontSize: '16px',
                        lineHeight: '1.5em',
                        fontFamily: 'Inter, sans-serif',
                        headings: {
                          fontFamily: 'Inter, sans-serif',
                          fontWeight: '600'
                        },
                        code: {
                          fontFamily: 'JetBrains Mono, monospace',
                          fontSize: '14px',
                          fontWeight: '400',
                          color: '#24292e',
                          backgroundColor: 'rgba(27,31,35,0.05)',
                          wrap: true
                        }
                      },
                      sidebar: {
                        backgroundColor: '#fafafa',
                        textColor: '#333333',
                        activeTextColor: '#2196f3',
                        width: '300px',
                        spacing: {
                          unit: 10,
                          paddingVertical: 20,
                          paddingHorizontal: 20
                        }
                      },
                      rightPanel: {
                        backgroundColor: '#f8f9fa',
                        width: '40%'
                      }
                    },
                    nativeScrollbars: true,
                    disableSearch: false,
                    requiredPropsFirst: true
                  },
                  document.getElementById('redoc')
                );
              </script>
              <style>
                body {
                  margin: 0;
                  padding: 0;
                  background-color: #ffffff;
                }
                #redoc {
                  min-height: 100vh;
                }
                .redoc-wrap {
                  background-color: #ffffff;
                }
                .api-content {
                  padding: 20px;
                }
                .operation-type {
                  border-radius: 3px;
                  font-family: 'JetBrains Mono', monospace;
                  font-size: 12px;
                  font-weight: 600;
                  padding: 4px 8px;
                }
                .response-title {
                  font-weight: 600;
                }
                pre {
                  border-radius: 4px;
                  margin: 0;
                }
                code {
                  font-family: 'JetBrains Mono', monospace !important;
                }
              </style>
            </body>
          </html>
          EOF

      - name: Copy OpenAPI file
        run: cp openapi.yaml docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 