name: Deploy API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate HTML documentation
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <title>PAXAFE Live Risk API Documentation</title>
              <meta charset="utf-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
              <style>
                body {
                  margin: 0;
                  padding: 0;
                }
                #redoc-container {
                  min-height: 100vh;
                }
              </style>
              <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
            </head>
            <body>
              <div id="redoc-container"></div>
              <script>
                Redoc.init(
                  'spec.yaml',
                  {
                    scrollYOffset: 50,
                    hideDownloadButton: false,
                    theme: {
                      colors: {
                        primary: {
                          main: '#2196f3'
                        }
                      },
                      typography: {
                        fontFamily: 'Inter, sans-serif',
                        headings: {
                          fontFamily: 'Inter, sans-serif'
                        }
                      }
                    }
                  },
                  document.getElementById('redoc-container')
                );
              </script>
            </body>
          </html>
          EOF

      - name: Copy OpenAPI spec
        run: |
          cp openapi.yaml docs/spec.yaml
          ls -la docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true 