name: Deploy API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate HTML documentation
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <title>PAXAFE Live Risk API Documentation</title>
              <meta charset="utf-8"/>
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
              <style>
                body {
                  margin: 0;
                  padding: 0;
                }
                #redoc-container {
                  min-height: 100vh;
                }
              </style>
              <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
            </head>
            <body>
              <div id="redoc-container"></div>
              <script>
                window.onload = function() {
                  Redoc.init(
                    window.location.origin + '/documentationsapi/openapi.yaml',
                    {
                      scrollYOffset: 50,
                      hideDownloadButton: false,
                      theme: {
                        colors: {
                          primary: {
                            main: '#2196f3'
                          }
                        },
                        typography: {
                          fontFamily: 'Inter, sans-serif',
                          headings: {
                            fontFamily: 'Inter, sans-serif'
                          }
                        }
                      }
                    },
                    document.getElementById('redoc-container'),
                    function(e) {
                      if (e) {
                        console.error('Failed to load spec:', e);
                        document.getElementById('redoc-container').innerHTML = 
                          '<p style="color: red; padding: 20px;">Error loading API documentation. Please check the console for details.</p>';
                      }
                    }
                  );
                };
              </script>
            </body>
          </html>
          EOF

      - name: Verify OpenAPI spec
        run: |
          if [ ! -f "openapi.yaml" ]; then
            echo "Error: openapi.yaml not found"
            exit 1
          fi
          echo "OpenAPI spec file size: $(wc -c < openapi.yaml) bytes"
          echo "OpenAPI spec first few lines:"
          head -n 5 openapi.yaml

      - name: Copy OpenAPI spec
        run: |
          cp openapi.yaml docs/openapi.yaml
          echo "Contents of docs directory:"
          ls -la docs/
          echo "Size of copied spec:"
          wc -c docs/openapi.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true 